
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Aws Configure
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-south-1


    - name: Copying the files
      run: 
        aws s3 sync . s3://study-edge-pydah1
